.model small
.data
    MSG1 DB 'DIGITE UM NUMERO DE 0 A 9:        ' , '$'
    MSG2 DB 'DIGITE OUTRO NUMERO DE 0 A 9:     ', '$'
    MSG3 DB 'MAIOR NUMERO:   ', '$'
    MSG4 DB ' / PARIDADE IMPAR', 10, '$'
    MSG5 DB ' / PARIDADE PAR', 10, '$'
    MSG6 DB 'MENOR NUMERO:   ', '$'
  
.code
    main proc
    MOV AX, @data ; INICIAR O @DATA
    MOV DS, AX

    MOV AH, 09   ; EXIBIR A PRIMEIRA MSG
    LEA DX, MSG1  
    INT 21H

    MOV AH, 01   ; LER O PRIMERO NUMERO
    INT 21H
    MOV BL, AL   ; MOVENDO O PRIMEIRO NUMERO LIDO PARA O REGISTRADOR BL

    MOV DL, 10  ; PULAR LINHA
    INT 21H
    MOV AH, 09    ; EXIBIR A SEGUNDA MSG
    LEA DX, MSG2  
    INT 21H

    MOV AH, 01   ; LER O SEGUNDO NUMERO
    INT 21H
    MOV BH, AL   ; MOVENDO O SEGUNDO NUMERO LIDO PARA O REGISTRADOR BH

    SUB BL, 30H  ; RETIRA 30H DE BL PARA SER LIDO COM UM NUMERO 
    SUB BH, 30H  ; RETIRA 30H DE BH PARA SER LIDO COM UM NUMERO
    CMP BH, BL   ; COMPARA OS DOIS NUMEROS LIDOS 
    JA MAIOR    ; CASO BH FOR MAIOR PULAR PARA MAIOR
    XCHG BH,BL  ; caso BL seja maior trocar os valores dos dois 

MAIOR:
    MOV DL, 10 ; PULAR LINHA
    INT 21H
    MOV AH, 09    
    LEA DX, MSG3 ; EXIBIR A TERCEIRA MENSAGEM
    INT 21H       
    
    ADD BH, 30H  ; ADICIONAR 30H PARA O NUMERO VOLTAR AO SEU VALOR NA TABELA ASCII E SER IMPRIMIDO
    MOV DL, BH   ; MOVEM O NUMERO DE BH PARA DL, PARA SER IMPRIMIDO A PARTIR DA FUNCAO 02
    MOV AH, 02   ; IMPRIMIR O MAIOR NUMERO QUE ESTA EM BH
    INT 21H   
  
    ADD BH, 0    ; IDENTIFICAR SE O MAIOR NUMERO É PAR  
    JP PAR1      ; CASO O MAIOR NUMERO SEJA PAR, PULAR PARA O PAR
    MOV AH, 09
    LEA DX, MSG4 ; EXIBIR A QUARTA MENSAGEM 
    INT 21H
    JMP MENOR ; PULAR PARA EXIBIR O MENOR NUMERO 
PAR1:
    MOV AH, 09
    LEA DX, MSG5
    INT 21H  ; imprime a mensagem se o primeiro numero é par ou impar 
    
MENOR:
    MOV AH, 09    
    LEA DX, MSG6 ; EXIBIR A SEXTA MENSAGEM
    INT 21H       
    
    ADD BL, 30H  ; ADICIONAR 30H PARA O NUMERO VOLTAR AO SEU VALOR NA TABELA ASCII E SER IMPRIMIDO
    MOV DL, BL   ; MOVEM O NUMERO DE BH PARA DL, PARA SER IMPRIMIDO A PARTIR DA FUNCAO 02
    MOV AH, 02   ; IMPRIMIR O MAIOR NUMERO QUE ESTA EM BH
    INT 21H   

    ADD BL, 0    ; IDENTIFICAR SE O MAIOR NUMERO É PAR  
    JP PAR2      ; CASO O MAIOR NUMERO SEJA PAR, PULAR PARA O PAR
    MOV AH, 09
    LEA DX, MSG4 ; EXIBIR A QUARTA MENSAGEM 
    INT 21H
    JMP FIM ; PULAR PARA O FINAL DO PROGRAMA, PARA NAO REPITIR O 
PAR2:
    MOV AH, 09
    LEA DX, MSG5
    INT 21H  ; imprime a mensagem se o primeiro numero é par ou impar 
FIM:
    MOV AH, 4Ch
    INT 21H

    MAIN ENDP
    END MAIN